# Copyright (C) 2021 Jingli Chen (Wine93), NetEase Inc.

###################### TOC #######################
# * _GLOBAL_
# * CONFIG
#   * _CONFIG_CLIENT_
#   * _CONFIG_ETCD_
#   * _CONFIG_MDS_
#   * _CONFIG_METASERVER_
#   * _CONFIG_SPACE_
#   * _CONFIG_TOOLS_
##################################################

################################################## _GLOBAL_
dingofs_project_home: "/home/nbs/machine/{{ inventory_hostname }}/dingofs"
dingofs_project_log_home: "/tmp/{{ inventory_hostname }}/dingofs"
dingofs_wait_service_timeout: 20
dingofs_debug_symbol_file_suffix: ".dbg-sym"
dingofs_core_method: "sync_direct"  # (sync_direct|sync_tarball|download_sync|deb|rpm)
dingofs_client_mount_path: "{{ client_mount_path }}"
dingofs_client_mount_args: >
  -o default_permissions
  -o allow_other
  -o fsname={{ client_mount_fsname }}
  -o fstype=s3
  -o user=test
  -f

################################################## _CONFIG_CLIENT_

################################################## _CONFIG_ETCD_
dingofs_etcd_listen_peer_host: "{{ ansible_ssh_host }}"
dingofs_etcd_listen_peer_port: "{{ etcd_listen_peer_port }}"
dingofs_etcd_listen_client_port: "{{ etcd_listen_client_port }}"
dingofs_etcd_data_dir: /tmp/{{ inventory_hostname }}/etcd_data
dingofs_etcd_wal_dir: /tmp/{{ inventory_hostname }}/etcd_wal

################################################## _CONFIG_MDS_
dingofs_mds_listen_host: "{{ ansible_ssh_host }}"
dingofs_mds_listen_port: "{{ mds_listen_port }}"
dingofs_mds_listen_dummy_port: "{{ mds_listen_dummy_port }}"

################################################## _CONFIG_METASERVER_
dingofs_metaserver_listen_host: "{{ ansible_ssh_host }}"
dingofs_metaserver_listen_port: "{{ metaserver_listen_port }}"
dingofs_metaserver_data_root: /tmp/{{ inventory_hostname }}/metaserver_data

################################################## _CONFIG_SPACE_
dingofs_space_listen_host: "{{ ansible_ssh_host }}"
dingofs_space_listen_port: "{{ space_listen_port }}"

################################################## _CONFIG_TOOLS_
dingofs_topology: "{{ groups.metaserver | smart_topology(hostvars, 3, 100) }}"

# NOTE: The topology are generated automatically according to the effective strategy,
# if you want to generate topology by yourself,
# you can set the below dingofs_topology variable by manually, e.g:
#
#dingofs_topology:
#  servers:
#    - name: server1
#      internalip: 127.0.0.1
#      internalport: 16701
#      externalip: 127.0.0.1
#      externalport: 16701
#      zone: zone1
#      pool: pool1
#    ...
#  pools:
#    - name: pool1
#      replicasnum: 3
#      copysetnum: 100
#      zonenum: 3
