# mds
# ├── conf
# │   └── mds.conf
# ├── logs
# │   └── mds.pid
# ├── sbin
# │   ├── servicectl
# │   └── dingofs-mds
# └── lib
#     └── mds_lib.so

project_name: "mds"
project_home: "{{ dingofs_project_home }}"
project_root_src: "{{ playbook_dir }}/projects/mds"
project_root_dest: "{{ project_home }}/mds"
project_log_root: "{{ dingofs_project_log_home }}/mds"
project_config_src: "{{ playbook_dir | dirname }}/conf"
project_config_dsv: "="
project_core_method: "{{ dingofs_core_method }}"
project_start_with_deamon: True
project_daemon: "{{ project_start_with_deamon | ternary('--daemon', '') }}"
project_listen_port: "{{ dingofs_mds_listen_dummy_port }}"
project_wait_service_timeout: "{{ dingofs_wait_service_timeout }}"
project_binary_debug_symbol_suffix: "{{ dingofs_debug_symbol_file_suffix }}"

project_templates:
  - mds.conf

project_directorys:
  - "{{ project_root_dest }}"
  - "{{ project_log_root }}"
