# metaserver
# ├── conf
# │   └── metaserver.conf
# ├── logs
# │   └── metaserevr.pid
# ├── sbin
# │   ├── servicectl
# │   └── dingofs-metaserver
# └── lib
#     └── metaserver_lib.so

project_name: "metaserver"
project_home: "{{ dingofs_project_home }}"
project_root_src: "{{ playbook_dir }}/projects/metaserver"
project_root_dest: "{{ project_home }}/metaserver"
project_log_root: "{{ dingofs_project_log_home }}/metaserver"
project_config_src: "{{ playbook_dir | dirname }}/conf"
project_config_dsv: "="
project_core_method: "{{ dingofs_core_method }}"
project_start_with_deamon: False
project_daemon: "{{ project_start_with_deamon | ternary('--daemon', '') }}"
project_listen_port: "{{ dingofs_metaserver_listen_port }}"
project_wait_service_timeout: "{{ dingofs_wait_service_timeout }}"
project_binary_debug_symbol_suffix: "{{ dingofs_debug_symbol_file_suffix }}"

project_templates:
  - metaserver.conf

project_directorys:
  - "{{ project_root_dest }}"
  - "{{ project_log_root }}"
  - "{{ dingofs_metaserver_data_root }}"
