# tools
# ├── conf
# │   └── tools.conf
# ├── logs
# │   └── tools.pid
# ├── sbin
# │   ├── servicectl
# │   └── dingofs-tools
# └── lib
#     └── tools_lib.so

project_name: "tools"
project_home: "{{ dingofs_project_home }}"
project_root_src: "{{ playbook_dir }}/projects/tools"
project_root_dest: "{{ project_home }}/tools"
project_log_root: "{{ dingofs_project_log_home }}/tools"
project_config_src: "{{ playbook_dir | dirname }}/conf"
project_config_dsv: "="
project_core_method: "{{ dingofs_core_method }}"
project_binary_debug_symbol_suffix: "{{ dingofs_debug_symbol_file_suffix }}"

project_templates:
  - tools.conf
  - topology.json

project_directorys:
  - "{{ project_root_dest }}"
  - "{{ project_log_root }}"
